### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by W-D0n** [W-Kamal/OhMyFood_3#3]
### Gobal

- [x] 1. Découpage maquette (==[Figma link](https://www.figma.com/file/qmGCiTpVPvpRnNib34L7Ks/P3-OhMyFood?node-id=0%3A1) )
- [x] 2. Repo github + first commit.
- [x] 3. Arborescence dossiers (root,assets,scripts).
- [x] 4. Structure général html.
- [x] 5. Récup des assets (images,charte couleurs, icones etc...).
- [x] 6. Définition des breakpoints en fonction des devices (mobile first+tab+desk).
- [x] 7. **Les animations sont jouées au clic sur mobile/tab !** _(breakpoints)_
- [x] 8. **Les animations sont jouées au survol sur desk !** _(breakpoints)_
- [x] 9. Pas de barre de défilement entre les différentes size de device.
- [x] 10. Résolution max 1920x1080.
- [x] 11. Transformer/Intégrer le code test créé avec codpen dans la prod.
- [x] 12. Supprimer la classe bg-test (classe temporaire) dans les balises html.
- [x] 13. Comprendre :before :after.
- [x] ~14. Apprendre et Structurer en pattern 7-1.~
- [x] 15. Mettre le :hover sur les lsit_items de la section fctmt
- [x] 16. Définir les conditions d'animations pour les éléments en desk/mobile...(:hover/:active...).
- [x] 17. Quelle pseudo-classe ou pseudo-element utiliser pour appliquer un param au SURVOL (cf mobile/tab)?
- [x] 19. Solve toutes les issues.
- [x] ~20. Trouver un moyen de mettre le coeur de like comme icone d'un input pour la cohérence avec le projet, cursor pointer n'est que peu cohérent fonctionnellement.~
- [x] 21. Vérifier les indentations (j'ai mis le désordre....).
- [x] 22. Vérifier la cohérence de mon organisation des fichiers....est-ce que j'ai besoin d'avoir autant de fichiers scss différents...(objectif:maintenabilité).
- [x] 23. Mettre suffisamment d'espace entre les icones et le textes du footer pour aligner les textes des liens.
- [x] ~24. Pour la partie responsive (passage en tab/desk) : utiliser les if~
- [x] ~25. Réfléchir au résultat d'une situation où les animations seraient désactivées par l'utilisateur (cf points 28 + 29).~
- [ ] 26. Clean du code !
- [x] 27. Modifier les unités utilisées : passer de full rem aux viewport (vh vw).
- [x] 28. mettre les param des animations en variables.
- [x] ~29. mediaQ pour l'annulation des animations par l'user ?~
- [x] ~30. Optimiser la base du css grâce aux retours des stats tels que css stats ou gtmetrix.~
- [x] 31. factoriser l'utilisation des déclarations davantage (display/width/height...).
- [x] 32. resizer les images (poids mo trop important...).
- [x] 33. mettre les paramètres typo dans _typo.scss
- [x] 34. mettre le svg du coeur like dans un bouton.
- [x] 35. mettre davantage de cohérence dans le nommage des class etc, et globalement dans le code (notamment la hiérarchie : position/boxmodel/typo/visual/miscellaneous).
